#page title
page_title                                : Veepy - Fast Private VPN                                          # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id                                :                                           # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).

appstore_link                             :                                           # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            :  https://play.google.com/store/apps/details?id=app.veepy&referrer=utm_source%3Dlanding                                         # Enter Google Play Store URL.
presskit_download_link                    :                                           # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file).
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  : assets/appicon.png                      # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  : Veepy                                          # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 : Fast Secure VPN                                         # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : VPN with built-in Malware blocking.

enable_smart_app_banner                   : false                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 :
your_link                                 : https://veepy.app
your_city                                 :
email_address                             :
facebook_username                         :
instagram_username                        :
twitter_username                          :
github_username                           :
youtube_username                          :



# Feature List                            Edit, add or remove features to be presented.
features                                  :
  - title                                 : Secure
    description                           : Quantum resistant cryptography<br/>Optional Malware Filtering<br/>Based on WireGuard, the modern standard for VPN security
    fontawesome_icon_name                 : lock

  - title                                 : Private
    description                           : No VPN logs.<br/>No accounts or signups.<br/>No commitment&#58 Get access by the day, week, or month - with an optional monthly subscription if desired.
    fontawesome_icon_name                 : user-secret

  - title                                 : Mobile First Design
    description                           : Perfect for roaming<br/>No more dropped connections when moving between networks.
    fontawesome_icon_name                 : mobile

  - title                                 : Fast
    description                           : Connect instantly
    fontawesome_icon_name                 : tachometer-alt

  - title                                 : Modern
    description                           : IPv6 Support
    fontawesome_icon_name                 : network-wired

  - title                                 : Themed
    description                           : Automatic Day / Night theme
    fontawesome_icon_name                 : adjust

  - title                                 : # New Feature Title
    description                           : # New Feature Description
    fontawesome_icon_name                 : # Enter Font Awesome icon name (e.g. star). Find icons on fontawesome.com/icons.



# Theme Settings
topbar_color                              : "#000000"
topbar_transparency                       : 0.1
topbar_title_color                        : "#ffffff"

cover_image                               : #assets/headerimage.png                    # Replace with alternative image path or image URL.
cover_overlay_color                       : "#000000"
cover_overlay_transparency                : 1.0

device_color                              : black                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#ffffff"

link_color                                : "#1d63ea"

app_title_color                           : "#1faa00"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#000000"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#1d63ea"
feature_icons_background_color            : "#e6e6e6"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#666666"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME
  - vendor
  - Gemfile
  - Gemfile.lock

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown

